import { writeFileSync } from 'fs';
import chalk from 'chalk';
import { readDecisionsAll, type Decision } from '../storage.js';

type Period = 'daily' | 'monthly';
type Format = 'csv' | 'json' | 'md';

interface PeriodStat {
  period: string;
  total: number;
  prompted: number;
  reviewed: number;
  rubber_stamped: number;
  bypassed: number;
  rubber_stamp_pct: number;
  avg_decision_ms: number | null;
  csi: number;
}

export function exportCommand(period: Period, format: Format, outFile: string | undefined) {
  const decisions = readDecisionsAll();

  if (decisions.length === 0) {
    console.log(chalk.dim('No data to export.'));
    return;
  }

  const grouped = groupByPeriod(decisions, period);
  const stats = grouped.map(([label, rows]) => computeStat(label, rows));
  const output = render(stats, format, period);

  if (outFile) {
    writeFileSync(outFile, output, 'utf8');
    console.log(chalk.green(`✓ Exported to ${outFile}`));
  } else {
    process.stdout.write(output);
  }
}

function groupByPeriod(decisions: Decision[], period: Period): [string, Decision[]][] {
  const map = new Map<string, Decision[]>();
  for (const d of decisions) {
    const date = new Date(d.ts);
    const key = period === 'daily'
      ? `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`
      : `${date.getFullYear()}-${pad(date.getMonth() + 1)}`;
    if (!map.has(key)) map.set(key, []);
    map.get(key)!.push(d);
  }
  return [...map.entries()].sort(([a], [b]) => a.localeCompare(b));
}

function computeStat(label: string, rows: Decision[]): PeriodStat {
  const reviewed = rows.filter(d => d.verdict === 'reviewed').length;
  const rubber_stamped = rows.filter(d => d.verdict === 'rubber_stamped').length;
  const bypassed = rows.filter(d => d.verdict === 'bypassed').length;
  const prompted = reviewed + rubber_stamped;
  const rubber_stamp_pct = prompted > 0 ? Math.round((rubber_stamped / prompted) * 100) : 0;

  const times = rows.filter(d => d.time_ms !== null).map(d => d.time_ms!);
  const avg_decision_ms = times.length > 0 ? Math.round(times.reduce((a, b) => a + b, 0) / times.length) : null;

  let weightedRS = 0, totalW = 0;
  for (const d of rows) {
    if (d.verdict === 'bypassed') continue;
    const w = 0.5 + d.complexity;
    totalW += w;
    if (d.verdict === 'rubber_stamped') weightedRS += w;
  }
  const csi = totalW > 0 ? Math.round((weightedRS / totalW) * 100) : 0;

  return { period: label, total: rows.length, prompted, reviewed, rubber_stamped, bypassed, rubber_stamp_pct, avg_decision_ms, csi };
}

function render(stats: PeriodStat[], format: Format, period: Period): string {
  if (format === 'json') return JSON.stringify(stats, null, 2) + '\n';
  if (format === 'csv') return renderCsv(stats);
  return renderMarkdown(stats, period);
}

function renderCsv(stats: PeriodStat[]): string {
  const header = 'period,total,prompted,reviewed,rubber_stamped,bypassed,rubber_stamp_pct,avg_decision_ms,csi';
  const rows = stats.map(s =>
    `${s.period},${s.total},${s.prompted},${s.reviewed},${s.rubber_stamped},${s.bypassed},${s.rubber_stamp_pct},${s.avg_decision_ms ?? ''},${s.csi}`
  );
  return [header, ...rows].join('\n') + '\n';
}

function renderMarkdown(stats: PeriodStat[], period: Period): string {
  const title = period === 'daily' ? 'Daily Report' : 'Monthly Report';
  const lines = [
    `# Cognitive Surrender — ${title}`,
    '',
    `| Period | Total | Prompted | Reviewed | Rubber-Stamped | Bypassed | Rubber-Stamp% | Avg Time | CSI |`,
    `|--------|------:|---------:|---------:|---------------:|---------:|--------------:|---------:|----:|`,
  ];
  for (const s of stats) {
    const avg = s.avg_decision_ms !== null ? `${(s.avg_decision_ms / 1000).toFixed(1)}s` : '—';
    lines.push(`| ${s.period} | ${s.total} | ${s.prompted} | ${s.reviewed} | ${s.rubber_stamped} | ${s.bypassed} | ${s.rubber_stamp_pct}% | ${avg} | ${s.csi} |`);
  }
  lines.push('', `*Generated by cognitive-surrender*`, '');
  return lines.join('\n');
}

function pad(n: number): string {
  return String(n).padStart(2, '0');
}
