import { writeFileSync } from 'fs';
import chalk from 'chalk';
import { openDb, type Decision } from '../db.js';

type Period = 'daily' | 'monthly';
type Format = 'csv' | 'json' | 'md';

interface PeriodStat {
  period: string;       // YYYY-MM-DD or YYYY-MM
  total: number;
  prompted: number;
  reviewed: number;
  surrendered: number;
  auto_approved: number;
  surrender_pct: number;
  avg_decision_ms: number | null;
  csi: number;
}

export function exportCommand(period: Period, format: Format, outFile: string | undefined) {
  const db = openDb();

  const decisions = db.prepare(
    'SELECT * FROM decisions ORDER BY timestamp_ms ASC'
  ).all() as Decision[];

  db.close();

  if (decisions.length === 0) {
    console.log(chalk.dim('No data to export.'));
    return;
  }

  const grouped = groupByPeriod(decisions, period);
  const stats = grouped.map(([label, rows]) => computeStat(label, rows));

  const output = render(stats, format, period);

  if (outFile) {
    writeFileSync(outFile, output, 'utf8');
    console.log(chalk.green(`✓ Exported to ${outFile}`));
  } else {
    process.stdout.write(output);
  }
}

function groupByPeriod(decisions: Decision[], period: Period): [string, Decision[]][] {
  const map = new Map<string, Decision[]>();
  for (const d of decisions) {
    const date = new Date(d.timestamp_ms);
    const key = period === 'daily'
      ? `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`
      : `${date.getFullYear()}-${pad(date.getMonth() + 1)}`;
    if (!map.has(key)) map.set(key, []);
    map.get(key)!.push(d);
  }
  return [...map.entries()].sort(([a], [b]) => a.localeCompare(b));
}

function computeStat(label: string, rows: Decision[]): PeriodStat {
  const reviewed = rows.filter(d => d.verdict === 'reviewed').length;
  const surrendered = rows.filter(d => d.verdict === 'surrendered').length;
  const auto = rows.filter(d => d.verdict === 'auto_approved').length;
  const prompted = reviewed + surrendered;
  const surrender_pct = prompted > 0 ? Math.round((surrendered / prompted) * 100) : 0;

  const times = rows.filter(d => d.decision_time_ms !== null).map(d => d.decision_time_ms!);
  const avg_decision_ms = times.length > 0
    ? Math.round(times.reduce((a, b) => a + b, 0) / times.length)
    : null;

  // Simple CSI: weighted surrender rate (no recency decay for exports — flat view per period)
  let weightedSurr = 0, totalW = 0;
  for (const d of rows) {
    if (d.verdict === 'auto_approved') continue;
    const w = 0.5 + d.complexity;
    totalW += w;
    if (d.verdict === 'surrendered') weightedSurr += w;
  }
  const csi = totalW > 0 ? Math.round((weightedSurr / totalW) * 100) : 0;

  return { period: label, total: rows.length, prompted, reviewed, surrendered, auto_approved: auto, surrender_pct, avg_decision_ms, csi };
}

function render(stats: PeriodStat[], format: Format, period: Period): string {
  if (format === 'json') return renderJson(stats);
  if (format === 'csv') return renderCsv(stats);
  return renderMarkdown(stats, period);
}

function renderJson(stats: PeriodStat[]): string {
  return JSON.stringify(stats, null, 2) + '\n';
}

function renderCsv(stats: PeriodStat[]): string {
  const header = 'period,total,prompted,reviewed,surrendered,auto_approved,surrender_pct,avg_decision_ms,csi';
  const rows = stats.map(s =>
    `${s.period},${s.total},${s.prompted},${s.reviewed},${s.surrendered},${s.auto_approved},${s.surrender_pct},${s.avg_decision_ms ?? ''},${s.csi}`
  );
  return [header, ...rows].join('\n') + '\n';
}

function renderMarkdown(stats: PeriodStat[], period: Period): string {
  const title = period === 'daily' ? 'Daily Report' : 'Monthly Report';
  const lines: string[] = [
    `# Cognitive Surrender — ${title}`,
    '',
    `| Period | Total | Prompted | Reviewed | Surrendered | Auto | Surrender% | Avg Time | CSI |`,
    `|--------|------:|---------:|---------:|------------:|-----:|-----------:|---------:|----:|`,
  ];

  for (const s of stats) {
    const avg = s.avg_decision_ms !== null ? `${(s.avg_decision_ms / 1000).toFixed(1)}s` : '—';
    lines.push(
      `| ${s.period} | ${s.total} | ${s.prompted} | ${s.reviewed} | ${s.surrendered} | ${s.auto_approved} | ${s.surrender_pct}% | ${avg} | ${s.csi} |`
    );
  }

  lines.push('');
  lines.push(`*Generated by cognitive-surrender*`);
  lines.push('');
  return lines.join('\n');
}

function pad(n: number): string {
  return String(n).padStart(2, '0');
}
